version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: dev-test
    path: src/
    text-resources:
      - path: lang/*.json
        format: nested-key-value
